NeuS added.
PaddlePaddle/Paddle3D pull request #319
Opened 2023-04-20 14:44 UTC by liu-vis

2023-04-21 03:28 UTC, will-jl944 commented on contrib/PaddleRendering/configs/instant-ngp/blender_data.yml
> +use_adaptive_ray_batch_size: False
这里为何需要修改？

2023-04-21 10:33 UTC, will-jl944 requested changes

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/configs/instant-ngp/blender_data.yml
> +use_adaptive_ray_batch_size: False
这里为何需要修改？

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/configs/instant-ngp/blender_data.yml
> +  dataset_root: /home/liuxing/workspace/datasets/nerf_synthetic/lego/
不要包含个人信息，且这里会跟教程文档不符

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/configs/instant-ngp/blender_data.yml
> +  dataset_root: /home/liuxing/workspace/datasets/nerf_synthetic/lego/
同上

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/configs/mip_nerf/blender_data.yml
> +  dataset_root: /home/liuxing/workspace/datasets/nerf_synthetic/lego/
同上

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/configs/mip_nerf/blender_data.yml
> +  neus_style: True
为什么mip-nerf的配置文件要包含NeuS相关信息？

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/configs/nerf/blender_data.yml
> -ray_batch_size: 1024
NeRF配置文件为何要修改？

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/configs/nerf/blender_data.yml
> +  dataset_root: /home/liuxing/workspace/datasets/nerf_synthetic/lego/
不要包含个人信息

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/configs/neus/llff_data.yml
> +metrics:
这里不会被识别，只会使用默认的metric。需要明确指定`train_metrics`以及`val_metrics`，参考其他模型配置文件。

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/configs/neus/llff_data.yml
> +  dataset_root : "/home/liuxing/workspace/datasets/dtu_scan105/"
不要包含个人信息。文档中已经建议用户将数据集软链至`data/`路径下，参考其他模型的配置文件

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/configs/neus/llff_data.yml
> +  dataset_root: "/home/liuxing/workspace/datasets/dtu_scan105/"
同上

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/configs/plenoxels/blender_data.yml
> -ray_batch_size: 4000
为何要修改plenoxels模型配置文件

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/configs/ref_nerf/shiny_blender_data.yml
> +ray_batch_size: 256
为何要修改refnerf模型配置文件？

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/apis/__init__.py
> +"""
不要包含无用信息或注释

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/apis/checkpoint.py
> +# !/usr/bin/env python3
这里没有必要，下同

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/apis/pipeline.py
> -
这里看起来没有过格式检查，应该是有空行的

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/apis/pipeline.py
> +                v = v.cpu()
为什么需要拷贝到cpu？这会导致你后面的concat是在cpu上做，会影响性能

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/apis/trainer.py
> +                    if hasattr(self.val_dataset, "max_eval_num"):
这种逻辑可以简化一下：
```python
max_eval_num = getattr(self.val_dataset, "max_eval_num", None)
```
下同

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/apis/trainer.py
> +                        mesh_resolution = 64  # Can be ignored when validate_mesh is disabled.
这里的注释意思是如果`validate_mesh`是`False`，这里的所有`if hasattr(...); else(...)`都是无用的吗？

如果是的话可以在最前面加上对`validate_mesh`的判断，否则现在的写法所有模型都会走这段代码。

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/apis/trainer.py
> +                    eval_ray_batch_size = min(
这里什么原因？爆显存吗？

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/apis/trainer.py
> +                print(
代码中所有涉及到打印的，统一调用paddle3d的logger

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/apis/trainer.py
> +                     validate_mesh: bool = None,
结合代码看，`validate_mesh`是否应该是字符串？

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/apis/trainer.py
> +                 validate_mesh: bool = None,
同上

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/apis/trainer.py
> +        if not validate_mesh is None:
`if validate_mesh is not None:`

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/apis/trainer.py
> +        skip_pixels = self.val_dataset.skip_pixels
这个参数跟dataset的关联性不强，用户想以多大的步长采样pixel应该跟dataset无关，因为采样pixel不是dataset的工作，而应该是像你这里写的camera的工作（`cameras.get_image_coords`）。dataset只用来负责提供图片和图片对应的相机模型。

如果这个`skip_pixels`参数只是为了加快评估速度，是不是作为`evaluate`函数的一个参数比较好？这样用户可以直接通过在运行tools/evaluate.py的时候指定不同的步长调整输出的mesh。

另外建议这个参数改名为`pixel_stride`，含义更明确一些。

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/apis/trainer.py
> +                        pixels, (im_h, im_w, 3)).unsqueeze(axis=0)
(im_h, im_w, -1)，会更严谨一些

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/apis/trainer.py
> +                image_batch["image"] = paddle.concat(new_image_batch, axis=0)
这里应该是stack而不是concat

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/apis/trainer.py
> +                output = inference_step_with_grad(self.model, ray_bundle,
什么情况下出于什么原因需要在评估的时候计算梯度？

是否有必要实现两种inference_step函数，区别仅是是否开启`@paddle.no_grad()`？是否可以写成：
```python
if eval_with_grad:
    output = inference_step()
else:
    with paddle.no_grad():
        output = inference_step()
```

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/apis/trainer.py
> +            if "normals" in output.keys():
`if "normals" in output`就可以了

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/apis/trainer.py
> +                normal_image = output["normals"].detach().cpu().numpy()
paddle中直接`.numpy()`就可以了，不需要detach和cpu

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/apis/trainer.py
> +                normal_image = output["normals"].detach().cpu().numpy()
这里的这些计算为什么要用numpy而不是用paddle?

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/apis/trainer.py
> +            del output
这里的目的是？

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/cameras/cameras.py
> +        if not intrinsics is None:
`if intrinsics is not None`，更符合python的规范

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/cameras/cameras.py
> +            self.fx = intrinsics[:, 0, 0]
此处的写法是对intrinsics的shape有严格限制的，必须是3-dimensional，建议改成更灵活的形式。如果用户指定的是二维的呢（所有图片的相机内参均相同的情况）？

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/cameras/cameras.py
> +    intrinsics: Union[np.ndarray, paddle.Tensor] = None
这里你修改后，Cameras会要求至少以一种方式指定相机内参（分别指定fx, fy, cx, cy或直接指定一个矩阵），而二者的默认值都是None，为防止用户没有通过任何一种方式指定内参（fx, fy, cx, cy, intrinsics都是None），下面两种方法选一：

1. 不要在这里提供两种初始化方式，只保留fx, fy, cx, cy一种初始化方式，在cameras外部讲intrinsics处理成fx, fy, cx, cy再创建Camera实例。因为本身即使提供了intrinsics矩阵初始化方式，也一定会在__init__函数中将其解析成fx, fy, cx, cy，所以并不会增加多余计算量

2. 两种初始化方式都提供，但要做检查，如果都是None，raise ValueError

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/cameras/cameras.py
> +    def generate_rays(self,
yapf==0.26的报错解决了吗，此处修改应该是yapf版本问题导致的。

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/cameras/cameras.py
> +        if self.centerize_coords:
`centerize_coords`这个参数想表达什么含义？为什么为True的时候，图像坐标（u, v）可以直接被用作相机坐标系坐标（x_coords, y_coords）？

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/cameras/cameras.py
> +        # [Todo] confirm the following. Not sure why this is fine.
这里不确定的是？

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/cameras/rays.py
> +    nears: paddle.Tensor = None
这里看起来不是基于最新的代码开发的。

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/data/datasets/llff.py
> +from glob import glob
这里看起来也没做格式检查，python自带的库、外部安装的库、项目内部的模块三者时间应该有空行。应该有空行的

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/data/datasets/llff.py
> +        # Load image
无用代码需要删掉

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/data/datasets/llff.py
> +            intrinsics_all.append(paddle.to_tensor(intrinsics, dtype='float32'))
Dataset中尽量使用numpy而不是Paddle，且Cameras默认place是cpu，这里to_tensor之后初始化Camera的时候还需要拷贝到cpu

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/models/encoders/neus_encoder.py
> +                 periodic_fns=[paddle.sin, paddle.cos]):
参数这样设计，无法在yml配置文件中进行指定，建议改成字符串：
```
type: NeuSEncoder
periodic_fns: ["sin", "cos"]
```

如果这个默认参数基本不需要修改，可以不提供。

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/models/fields/neus_fields.py
> +class NeRFPPField(BaseField):
是否可以继承NeRFFIeld，只做部份修改？

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/models/fields/neus_fields.py
> +        #dirs = ray_samples.frustums.directions[:, None, :].expand(pts.shape)
无用代码需要删掉

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/models/fields/neus_fields.py
> +        #print('variance', self.variance)
无用代码需要删掉

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/models/layers/mlps.py
> +    nn.Softplus,
这里修改的原因是？

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/models/layers/mlps.py
> +        if not weight_init is None:
is not None

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/models/layers/mlps.py
> +                #raise NotImplementedError()
无用代码需要删掉

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/models/layers/mlps.py
> +                 activation: Union[str, List] = "relu",
这里的设计过于复杂了。建议改成：
```python
activation: Union[str, nn.Layer] = "relu"
```
然后如果需要在配置文件中
```
type: MLP
activation:
    type: Softplus
    beta: xxx
    threshold: xxx
```

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/models/neus/neus.py
> +                    # [NOTE] Check include_original = False.
写给自己的注释去掉一下

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/models/neus/neus.py
> +                    if not i + 1 == self.fine_sampling_steps:
`if i + 1 !=`

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/models/neus/neus.py
> +                        xx = paddle.expand(
xx变量名建议改一下，与实际含义相关

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/models/neus/neus.py
> +        #        if self.num_importance > 0:
无用代码需要去掉

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/models/neus/neus.py
> +        print('threshold: {}'.format(threshold))
print同意使用paddlerendering的logger。

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/models/neus/neus.py
> +                        t2 = time.time()
这一行什么作用

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/models/neus/neus.py
> +                                           len(zs))).detach().cpu().numpy()
paddle可以直接numpy()

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/models/ray_samplers/spaced_samplers.py
> +        s_nears = self.spacing_fn(ray_bundle.nears)
这里不是最新的代码

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/ray_marching.py
> +from pprndr.cameras.rays import Frustums, RayBundle, RaySamples
import顺序应该为：
1. python自带
2. 外部安装
3. 项目中的文件或模块

2023-04-21 10:33 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/ray_marching.py
> +    #prev_sdf = signed_distances[:, :-1, :] # [b, n_samples]
去掉无用代码

2023-04-23 07:45 UTC, liu-vis commented on contrib/PaddleRendering/configs/instant-ngp/blender_data.yml
> +use_adaptive_ray_batch_size: False
Done.

2023-04-23 07:46 UTC, liu-vis commented on contrib/PaddleRendering/configs/instant-ngp/blender_data.yml
> +  dataset_root: /home/liuxing/workspace/datasets/nerf_synthetic/lego/
Done.

2023-04-23 08:09 UTC, liu-vis commented on contrib/PaddleRendering/configs/instant-ngp/blender_data.yml
> +  dataset_root: /home/liuxing/workspace/datasets/nerf_synthetic/lego/
Done.

2023-04-23 08:10 UTC, liu-vis commented on contrib/PaddleRendering/configs/mip_nerf/blender_data.yml
> +  dataset_root: /home/liuxing/workspace/datasets/nerf_synthetic/lego/
Done. 
nerf/blender_data.yml, done.
neus/llff_data.yml, done.
plenoxels/blender_data.yml, done.
ref_nerf/shiny_blender_data.yml, done.

2023-04-23 08:12 UTC, liu-vis commented on contrib/PaddleRendering/configs/mip_nerf/blender_data.yml
> +  neus_style: True
"neus_style: " removed.

2023-04-23 08:16 UTC, liu-vis commented on contrib/PaddleRendering/configs/nerf/blender_data.yml
> -ray_batch_size: 1024
Done.

2023-04-23 08:16 UTC, liu-vis commented on contrib/PaddleRendering/configs/nerf/blender_data.yml
> +  dataset_root: /home/liuxing/workspace/datasets/nerf_synthetic/lego/
Done.

2023-04-23 08:18 UTC, liu-vis commented on contrib/PaddleRendering/configs/neus/llff_data.yml
> +metrics:
Done.

2023-04-23 08:18 UTC, liu-vis commented on contrib/PaddleRendering/configs/neus/llff_data.yml
> +  dataset_root : "/home/liuxing/workspace/datasets/dtu_scan105/"
Done.

2023-04-23 08:19 UTC, liu-vis commented on contrib/PaddleRendering/configs/neus/llff_data.yml
> +  dataset_root: "/home/liuxing/workspace/datasets/dtu_scan105/"
Done.

2023-04-23 08:20 UTC, liu-vis commented on contrib/PaddleRendering/configs/plenoxels/blender_data.yml
> -ray_batch_size: 4000
Done.

2023-04-23 08:21 UTC, liu-vis commented on contrib/PaddleRendering/configs/ref_nerf/shiny_blender_data.yml
> +ray_batch_size: 256
Done.

2023-04-23 08:23 UTC, liu-vis commented on contrib/PaddleRendering/pprndr/apis/__init__.py
> +"""
Done.

2023-04-23 08:28 UTC, liu-vis commented on contrib/PaddleRendering/pprndr/apis/pipeline.py
> -
Done.

2023-04-23 08:28 UTC, liu-vis commented on contrib/PaddleRendering/pprndr/apis/pipeline.py
> +                v = v.cpu()
Done.

2023-04-23 08:35 UTC, liu-vis commented on contrib/PaddleRendering/pprndr/apis/trainer.py
> +                    if hasattr(self.val_dataset, "max_eval_num"):
Done.

2023-04-23 08:49 UTC, liu-vis commented on contrib/PaddleRendering/pprndr/apis/trainer.py
> +                        mesh_resolution = 64  # Can be ignored when validate_mesh is disabled.
Done.

2023-04-23 08:57 UTC, liu-vis commented on contrib/PaddleRendering/pprndr/apis/trainer.py
> +                    eval_ray_batch_size = min(
Done. 
> 这里什么原因？爆显存吗？
   当evaluate_with_grad的时候, 会爆显存.

Updated:
eval_ray_batch_size = self.train_data_manager.ray_batch_size
...
eval_with_grad = getattr(self.val_dataset, "eval_with_grad", False)
if eval_with_grad:
    eval_ray_batch_size = min(256, self.train_data_manager.ray_batch_size)

2023-04-23 09:00 UTC, liu-vis commented on contrib/PaddleRendering/pprndr/apis/trainer.py
> +                print(
Done.

2023-04-23 09:08 UTC, liu-vis commented on contrib/PaddleRendering/pprndr/apis/trainer.py
> +                     validate_mesh: bool = None,
是的, done.

2023-04-23 09:10 UTC, liu-vis commented on contrib/PaddleRendering/pprndr/apis/trainer.py
> +                 validate_mesh: bool = None,
Done.

2023-04-23 09:11 UTC, liu-vis commented on contrib/PaddleRendering/pprndr/apis/trainer.py
> +        if not validate_mesh is None:
Done.

2023-04-23 09:14 UTC, liu-vis commented on contrib/PaddleRendering/pprndr/apis/checkpoint.py
> +# !/usr/bin/env python3
Done.

2023-04-23 11:02 UTC, liu-vis commented on contrib/PaddleRendering/pprndr/apis/trainer.py
> +        skip_pixels = self.val_dataset.skip_pixels
Done.

2023-04-23 11:03 UTC, liu-vis commented on contrib/PaddleRendering/pprndr/apis/trainer.py
> +                        pixels, (im_h, im_w, 3)).unsqueeze(axis=0)
Done.

2023-04-23 11:06 UTC, liu-vis commented on contrib/PaddleRendering/pprndr/apis/trainer.py
> +                image_batch["image"] = paddle.concat(new_image_batch, axis=0)
Done.

2023-04-24 02:09 UTC, liu-vis commented on contrib/PaddleRendering/pprndr/apis/trainer.py
> +                output = inference_step_with_grad(self.model, ray_bundle,
Q1: 什么情况下出于什么原因需要在评估的时候计算梯度？
R1: 一般会通过看采样点的normal渲染图，判断sdf训练是否正常。Normal由Gradient计算得出，因此inference的时候需要计算梯度
-------
Q2: 是否有必要实现两种inference_step函数
R2: inference with grad时，每个iter需要将ray_batch的output放到cpu上，不然有爆显存问题。这里与 inference w/o grad不同，如下：
inference w/ grad:
` for k, v in outputs.items():
       if isinstance(v, paddle.Tensor):
           v = v.cpu()
       ...`
inference w/o grad:
       `for k, v in outputs.items():
               ...`

2023-04-24 02:24 UTC, liu-vis commented on contrib/PaddleRendering/pprndr/apis/trainer.py
> +            if "normals" in output.keys():
Done.

2023-04-24 03:06 UTC, liu-vis commented on contrib/PaddleRendering/pprndr/apis/trainer.py
> +                normal_image = output["normals"].detach().cpu().numpy()
Done.

2023-04-24 03:21 UTC, liu-vis commented on contrib/PaddleRendering/pprndr/apis/trainer.py
> +            del output
在inference_with_grad的情况下，不 del output 的话，会在CPU内残留数据导致内存增长。不残留在GPU内的原因是inference_with_grad函数中会把output内的数据放到CPU上。

2023-04-24 03:23 UTC, liu-vis commented on contrib/PaddleRendering/pprndr/cameras/cameras.py
> +        if not intrinsics is None:
Done.

2023-04-24 04:33 UTC, liu-vis commented on contrib/PaddleRendering/pprndr/cameras/cameras.py
> +            self.fx = intrinsics[:, 0, 0]
Done.

2023-04-24 05:02 UTC, liu-vis commented on contrib/PaddleRendering/pprndr/cameras/cameras.py
> +    intrinsics: Union[np.ndarray, paddle.Tensor] = None
Done. 采用方法2.
不采用方法1的原因考虑如下：
在尽量不改动原版代码的前提下，如果在外部将intrinsics处理成fx, fy, cx, cy并以之创建Cameras实例的话，貌似要求fx, fy, cx, cy 只能各自是一个值。也就是说，不能覆盖到每张数据图片以不同的相机内参拍摄的情况（理论上来说，我们不应该限制用户只能使用同一个相机拍摄图片；比如用户想把多个相机绑定在一个 frame上，然后同时拍摄，这样的话每张图片就可能对应着不同的内参矩阵）。如果采取方法2的话，只要传入正确的intrinsics即可。

2023-04-24 05:06 UTC, liu-vis commented on contrib/PaddleRendering/pprndr/cameras/cameras.py
> +    def generate_rays(self,
这个好像没了。。

2023-04-24 05:30 UTC, liu-vis commented on contrib/PaddleRendering/pprndr/cameras/cameras.py
> +        if self.centerize_coords:
这个好像是显示的问题，导致不好理解逻辑。
centerize_coords参数表达是否对坐标进行中心化。中心化过后的坐标的（0，0）点是图片中心（假设cx, cy分别是W // 2, H // 2）；没中心化的话，坐标（0，0）点在左上角

2023-04-24 05:48 UTC, liu-vis commented on contrib/PaddleRendering/pprndr/cameras/cameras.py
> +        # [Todo] confirm the following. Not sure why this is fine.
计算directions的方式有些存疑，当前版本计算direcitons的流程为
directions = F.normalize(pixel_coords @ c2w, p=2)

我理解的正确的计算方式为
pts = intrinsic_inv @ pixel_coords
pts_norm = F.normalize(pts, p=2)
pts = pts / pts_norm
directions = c2w_mat @ pts

2023-04-24 05:56 UTC, liu-vis commented on contrib/PaddleRendering/pprndr/data/datasets/llff.py
> +        # Load image
Done.

2023-04-24 10:17 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/cameras/cameras.py
> +    intrinsics: Union[np.ndarray, paddle.Tensor] = None
> 貌似要求fx, fy, cx, cy 只能各自是一个值。

没有这个限制的，设计的时候已经考虑了你说的情况。相机内参和外参，在构造相机实例的时候，都支持包含batch的维度，即对应每张图片来自于不同参数的相机的情况。例如相机内参`fx`，可以是一个`float`传进来，也可以是shape为`[1]`或者`[num_images]`的`np.ndarray`或者`paddle.Tensor`.

2023-04-25 03:42 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/apis/trainer.py
> +                output = inference_step_with_grad(self.model, ray_bundle,
可以给`inference_step`函数加一个`to_cpu`参数，出于如下考虑：

1. 尽量遵循最大化复用的原则，相同或者非常相近的逻辑尽量复用，代码简洁且维护成本低
2. 从代码的逻辑来看，爆显存不一定会仅发生在带梯度的评估，也可能因为数据集过大，因此`to_cpu`对no_grad的评估也同样适用。

2023-04-25 04:35 UTC, liu-vis commented on contrib/PaddleRendering/pprndr/data/datasets/llff.py
> +            intrinsics_all.append(paddle.to_tensor(intrinsics, dtype='float32'))
Done.

2023-04-25 04:37 UTC, liu-vis commented on contrib/PaddleRendering/pprndr/models/encoders/neus_encoder.py
> +                 periodic_fns=[paddle.sin, paddle.cos]):
Done.

2023-04-25 04:42 UTC, liu-vis commented on contrib/PaddleRendering/pprndr/models/fields/neus_fields.py
> +        #dirs = ray_samples.frustums.directions[:, None, :].expand(pts.shape)
Done.

2023-04-25 04:42 UTC, liu-vis commented on contrib/PaddleRendering/pprndr/models/fields/neus_fields.py
> +        #print('variance', self.variance)
Done.

2023-04-25 04:50 UTC, liu-vis commented on contrib/PaddleRendering/pprndr/models/layers/mlps.py
> +    nn.Softplus,
为了能够在 初始化的时候这只softplus的两个参数，如下：

2023-04-25 04:53 UTC, liu-vis commented on contrib/PaddleRendering/pprndr/models/layers/mlps.py
> +        if not weight_init is None:
Done.

2023-04-25 12:45 UTC, liu-vis commented on contrib/PaddleRendering/pprndr/models/layers/mlps.py
> +                 activation: Union[str, List] = "relu",
Done.

2023-04-25 12:46 UTC, liu-vis commented on contrib/PaddleRendering/pprndr/models/layers/mlps.py
> +                #raise NotImplementedError()
Done.

2023-04-25 12:50 UTC, liu-vis commented on contrib/PaddleRendering/pprndr/models/neus/neus.py
> +                    # [NOTE] Check include_original = False.
Done.

2023-04-25 12:50 UTC, liu-vis commented on contrib/PaddleRendering/pprndr/models/neus/neus.py
> +                    if not i + 1 == self.fine_sampling_steps:
Done.

2023-04-25 13:07 UTC, liu-vis commented on contrib/PaddleRendering/pprndr/models/neus/neus.py
> +                        xx = paddle.expand(
Done.

2023-04-25 13:08 UTC, liu-vis commented on contrib/PaddleRendering/pprndr/models/neus/neus.py
> +        #        if self.num_importance > 0:
Done.

2023-04-25 13:08 UTC, liu-vis commented on contrib/PaddleRendering/pprndr/models/neus/neus.py
> +        print('threshold: {}'.format(threshold))
Done.

2023-04-25 13:09 UTC, liu-vis commented on contrib/PaddleRendering/pprndr/models/neus/neus.py
> +                        t2 = time.time()
Done.

2023-04-25 13:09 UTC, will-jl944 requested changes

2023-04-25 13:09 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/ray_marching.py
> +    # Not sure why the filtering is needed.
去掉这一行吧

2023-04-25 13:09 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/ray_marching.py
> +    prev_cdf = nn.Sigmoid()(estimated_prev_sdf * inv_s)
这里使用`import paddle.nn.functional as F; F.sigmoid(estimated_prev_sdf * inv_s)`比较好

2023-04-25 13:10 UTC, liu-vis commented on contrib/PaddleRendering/pprndr/models/neus/neus.py
> +                                           len(zs))).detach().cpu().numpy()
Done.

2023-04-25 13:11 UTC, liu-vis commented on contrib/PaddleRendering/pprndr/ray_marching.py
> +from pprndr.cameras.rays import Frustums, RayBundle, RaySamples
Done.

2023-04-25 13:12 UTC, liu-vis commented on contrib/PaddleRendering/pprndr/ray_marching.py
> +    #prev_sdf = signed_distances[:, :-1, :] # [b, n_samples]
Done.

2023-04-25 13:13 UTC, liu-vis commented on contrib/PaddleRendering/pprndr/ray_marching.py
> +    # Not sure why the filtering is needed.
Done.

2023-04-26 11:35 UTC, liu-vis commented on contrib/PaddleRendering/pprndr/apis/trainer.py
> +                output = inference_step_with_grad(self.model, ray_bundle,
Done.

2023-04-26 11:39 UTC, liu-vis commented on contrib/PaddleRendering/pprndr/cameras/rays.py
> +    nears: paddle.Tensor = None
fetched, updated.

2023-04-26 14:48 UTC, liu-vis commented on contrib/PaddleRendering/pprndr/models/fields/neus_fields.py
> +class NeRFPPField(BaseField):
Done.

2023-04-27 01:48 UTC, liu-vis commented on contrib/PaddleRendering/pprndr/ray_marching.py
> +    prev_cdf = nn.Sigmoid()(estimated_prev_sdf * inv_s)
Done.

2023-04-28 02:56 UTC, will-jl944 requested changes

2023-04-28 02:56 UTC, will-jl944 commented on contrib/PaddleRendering/configs/instant-ngp/blender_data.yml
> +eval_pixel_stride: 1
这里有验证过eval_pixel_stride > 1吗？

2023-04-28 02:56 UTC, will-jl944 commented on contrib/PaddleRendering/configs/mip_nerf/blender_data.yml
> +  centerize_coords: True
这个参数是不是已经没有用了？

2023-04-28 02:56 UTC, will-jl944 commented on contrib/PaddleRendering/configs/mip_nerf/blender_data.yml
> +  centerize_coords: True
同上

2023-04-28 02:56 UTC, will-jl944 commented on contrib/PaddleRendering/configs/instant-ngp/blender_data.yml
> -  dataset_root: data/nerf_synthetic/lego
这里的修改没有必要，不需要特意加上`/`，下同

2023-04-28 02:56 UTC, will-jl944 commented on contrib/PaddleRendering/configs/nerf/blender_data.yml
> -  dataset_root: data/nerf_synthetic/lego
这里是不是该错文件了，这个文件时nerf在blender dataset上的训练配置

2023-04-28 02:56 UTC, will-jl944 commented on contrib/PaddleRendering/configs/nerf/blender_data.yml
> -  dataset_root: data/nerf_synthetic/lego
同上

2023-04-28 02:56 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/apis/trainer.py
> +    #@paddle.no_grad()
这个注释可以去掉

2023-04-28 02:56 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/apis/trainer.py
> +        image_coords = cameras.get_image_coords(
这里offset是不是该懂了之前其他模型的逻辑（其他模型是0.5）？

2023-04-28 02:56 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/apis/trainer.py
> +            #            if eval_with_grad:
去掉无用注释

2023-04-28 02:56 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/cameras/cameras.py
> +    fx: Union[np.ndarray, paddle.Tensor, float] = None
这里应该去掉fx, fy, cx, cy, image_height, image_width的默认值，因为他们是必须参数。

2023-04-28 02:56 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/cameras/cameras.py
> -            fx: Union[np.ndarray, paddle.Tensor, float],
同上

2023-04-28 02:56 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/cameras/rays.py
> +            #sample_pad = euclidean_bins[:, -1:, :] + sample_dist
去掉无用注释

2023-04-28 02:56 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/cameras/rays.py
> +    nears: paddle.Tensor = None
这里的nears, fars属性是你新增的吗？

2023-04-28 02:56 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/data/datasets/blender.py
> +                 centerize_coords: bool = True,
`centerize_coords`还需要吗？

2023-04-28 02:56 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/data/datasets/blender.py
> +                 skip_pixels: int = 1.0,
`skip_pixels`是是生成rays时候的`pixel_stride`吗？是的话统一一下命名。

2023-04-28 02:56 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/data/datasets/blender.py
> +                 neus_style: bool = False,
`neus_style`参数的作用是？

2023-04-28 02:56 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/data/datasets/blender.py
> +            centerize_coords=self.centerize_coords,
这个参数还需要吗？

2023-04-28 02:56 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/models/encoders/neus_encoder.py
> +        #return output, self.output_dim
去掉无用注释

2023-04-28 02:56 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/models/fields/neus_fields.py
> +        # load torch sdf network weight
这段逻辑需要去掉

2023-04-28 02:56 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/models/fields/neus_fields.py
> +#@manager.FIELDS.add_component
去掉无用代码

2023-04-28 02:56 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/models/layers/mlps.py
> +class Softplus(nn.Layer):
不需要实现这个，解析yaml文件的时候如果不是pprndr注册的模块，会自动调用paddle.nn.Softplus。代码逻辑见https://github.com/PaddlePaddle/Paddle3D/blob/develop/contrib/PaddleRendering/pprndr/apis/config.py#L276

2023-04-28 02:56 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/models/neus/__init__.py
> +"""
去掉hi

2023-04-28 02:56 UTC, will-jl944 commented on contrib/PaddleRendering/tools/extract_mesh.py
> +sys.path.insert(1, "/home/liuxing/workspace/Paddle3D/contrib/PaddleRendering/")
不需要这一行，文档里已经建议用户export PYTHONPATH

2023-04-28 02:56 UTC, will-jl944 commented on contrib/PaddleRendering/tools/train.py
> +sys.path.insert(1, "/home/liuxing/workspace/Paddle3D/contrib/PaddleRendering/")
同上，不需要这一行

2023-04-28 14:07 UTC, liu-vis commented on contrib/PaddleRendering/configs/instant-ngp/blender_data.yml
> +eval_pixel_stride: 1
Done. 
All checked.

2023-05-02 15:10 UTC, liu-vis commented on contrib/PaddleRendering/configs/mip_nerf/blender_data.yml
> +  centerize_coords: True
Done.

2023-05-02 15:10 UTC, liu-vis commented on contrib/PaddleRendering/configs/mip_nerf/blender_data.yml
> +  centerize_coords: True
Done.

2023-05-02 15:11 UTC, liu-vis commented on contrib/PaddleRendering/configs/instant-ngp/blender_data.yml
> -  dataset_root: data/nerf_synthetic/lego
Done.

2023-05-02 15:17 UTC, liu-vis commented on contrib/PaddleRendering/pprndr/apis/trainer.py
> +    #@paddle.no_grad()
Done.

2023-05-02 15:25 UTC, liu-vis commented on contrib/PaddleRendering/pprndr/apis/trainer.py
> +        image_coords = cameras.get_image_coords(
是的，已经改为读取config文件中val_dataset里设定的offset。

2023-05-02 15:27 UTC, liu-vis commented on contrib/PaddleRendering/pprndr/apis/trainer.py
> +            #            if eval_with_grad:
Done.

2023-05-05 06:02 UTC, will-jl944 requested changes

2023-05-05 06:02 UTC, will-jl944 commented on contrib/PaddleRendering/configs/instant-ngp/blender_data.yml
> +eval_pixel_stride: 4
除NeuS以外其他模型验证过eval_pixel_stride就可以了，不需要修改配置文件

2023-05-05 11:31 UTC, will-jl944 approved these changes

2023-05-06 06:05 UTC, merged