[Hackathon No.175] Add TensoRF to PaddleRendering
PaddlePaddle/Paddle3D pull request #321
Opened 2023-04-27 08:04 UTC by kongdebug

为PaddleRendering新增TensoRF模型。为了实现原repo的网络参数上采样，对config.py与trainer.py以及grid.py新增了函数，没有删除的操作

2023-04-27 08:09 UTC, kongdebug commented
@will-jl944 麻烦老师review一下~

2023-04-27 11:19 UTC, will-jl944 requested changes

2023-04-27 11:19 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/models/layers/grids.py
> +        binary = paddle.zeros([self.num_voxels], dtype="bool")
这里对binary的更新是不是通过旧的binary来计算更合理？

2023-04-27 11:19 UTC, will-jl944 commented on contrib/PaddleRendering/pprndr/models/layers/grids.py
> +        occupancies = paddle.zeros([self.num_voxels])
occupancies同上

2023-04-28 06:47 UTC, kongdebug commented on contrib/PaddleRendering/pprndr/models/layers/grids.py
> +        binary = paddle.zeros([self.num_voxels], dtype="bool")
已修改

2023-04-28 06:47 UTC, kongdebug commented on contrib/PaddleRendering/pprndr/models/layers/grids.py
> +        occupancies = paddle.zeros([self.num_voxels])
已修改

2023-04-28 08:53 UTC, will-jl944 approved these changes
LGTM

2023-04-28 09:59 UTC, merged